name: Build Wheels
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          pybuilds: cp3{10,11,12}-manylinux_x86_64
          arch: x86_64
          id: linux_x86_64
        - os: ubuntu-24.04-arm
          pybuilds: cp3{10,11,12}-manylinux_aarch64
          arch: aarch64
          id: linux_arm64
        - os: macos-13
          pybuilds: cp3{10,11,12}-macosx_x86_64
          arch: x86_64
          id: macos_x86
        - os: macos-15
          pybuilds: cp3{10,11,12}-macosx_arm64
          arch: arm64
          id: macos_arm64
        - os: windows-latest
          pybuilds: cp3{10,11,12}-win_amd64
          arch: amd64
          id: windows_amd64
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: "Install Windows dependencies via vcpkg"
        if: runner.os == 'Windows'
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          vcpkgGitCommitId: da4b78d35084ec4e9808aa02017028da03b8d2ab
          vcpkgTriplet: 'x64-windows'
          vcpkgArguments: >
            boost-dynamic-bitset
            boost-filesystem
            boost-graph
            boost-odeint
            boost-program-options
            boost-serialization
            boost-system
            boost-test
            eigen3
            flann

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.0
        with:
          package-dir: py-bindings
        env:
          CIBW_ARCHS_MACOS: ${{ matrix.arch }}
          OMPL_BUILD_ARCH: ${{ matrix.arch }}
          CIBW_BUILD: ${{ matrix.pybuilds }}
          CIBW_SKIP: "cp*-manylinux_i686 cp*-musllinux* cp*-win32"
          CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET="15.0"
          CIBW_BEFORE_ALL_WINDOWS: ""
          CIBW_BEFORE_BUILD_WINDOWS: "bash .github/workflows/before_build_windows.sh"
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.arch }}
          path: wheelhouse

  prerelease:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    concurrency:
      group: push-${{ github.ref_name }}-prerelease
      cancel-in-progress: true
    needs: [build_wheels]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: wheelhouse
          pattern: wheels-*
          merge-multiple: true

      - name: GitHub release
        uses: ncipollo/release-action@v1.15.0
        with:
          prerelease: true
          tag: "prerelease"
          name: "Development Build"
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
          artifacts: "wheelhouse/*"

  publish_pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build_wheels
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download wheels artifact
        uses: actions/download-artifact@v4
        with:
          path: wheelhouse
          pattern: wheels-*
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          packages: wheelhouse/*.whl
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
